### ISSUE TITLE
Error: Can't resolve '@angular/cdk/rxjs'

### ISSUE THREAD

**Issue by machucarro** [Centroida/ngx-image-editor#8]
the ngx-image-editor.es5.js provided in the npm package version 1.3.0 has a reference to @angular/cdk/rxjs which throws an error because it has been removed from angular/cdk in Angular 5

https://stackoverflow.com/questions/47199138/error-cant-resolve-angular-cdk-rxjs

Steps to reproduce:
- Create a project with Angular 5.1.2 (can use CLI)
- Run ngx-image-editor install instructions with latest angular material and flex layout versions
- Import NgxImageEditorModule in AppModule
- run ng serve

**Comment by mikael-brochu** [comment]
Have you found a fix? At least something temporary?

**Comment by Taulantdisha** [comment]
The reason it doesn't work is because the editor is using angular material 2 and an older version of angular flex layout. Once i upgrade them the latest versions you will be good to use with the latest versions of Angular, Angular Material and Angular Flex Layout. I will upgrade everything this weekend.

**Comment by Taulantdisha** [comment]
I upgraded the dependencies so everything should be fine now.
